Update README.md
nuts-foundation/jwt-generator pull request #4
Opened 2023-03-13 08:57 UTC by beardedfoo

Adding more usage examples as well as installation and build instructions

2023-03-15 14:36 UTC, gerardsn requested changes

2023-03-15 14:36 UTC, gerardsn commented on README.md
> +chmod +x /usr/local/bin/nuts-jwt-generator $BINARY_URL
```suggestion
chmod +x /usr/local/bin/nuts-jwt-generator
```

2023-03-15 15:18 UTC, beardedfoo commented on README.md
> +## Usage
PEM/JWK/OpenSSH at the moment. We provide examples for all of these, but maybe it helps to explicitly mention the supported types?

2023-03-15 20:59 UTC, gerardsn commented on README.md
> +## Usage
Yes I think explicitly mentioning them is a good idea.

The intent of my original question was more along the lines RSA, elliptic curve ... and different key sizes. Should we mention something about that as well?

2023-03-16 15:31 UTC, gerardsn approved these changes

2023-03-16 15:31 UTC, merged